"""
training.py - RL hyperparameters, reward weights, and episode/checkpoint limits.
"""

MEAN_STATS_WINDOW = 20

# Reward weights
BOSS_PARAMETER = 1
DODGE_REWARD = 1.5

PLAYER_PARAMETER = 1
PLAYER_VULNERABILITY_EXP = 2

MIN_COMBAT_DEATH_PENALTY = 3
FALL_DEATH_PENALTY = 5
FALL_DEATH_HP_THRESHOLD = 0.75
GREEDY_PENALTY = 3

STAMINA_EXP = 3
LOW_STAMINA_PUNISH = 0.1

STEP_PENALTY = 0.05

REWARD_BOSS_DEFEATED = 100.0

# Reward history windows (in steps; 0.2s each, max possible = HISTORY_LENGTH)
DODGE_WINDOW = 10
GREEDY_WINDOW = 6
MULTIHIT_WINDOW = 10

# Episode (unbounded: episodes end only on death or victory, never a step limit)
HISTORY_LENGTH = 24
BOSS_DEFEAT_HP_THRESHOLD = 0.005

# PPO
LEARNING_RATE = 2e-4
N_STEPS = 2048
BATCH_SIZE = 512
N_EPOCHS = 6
GAMMA = 0.96
ENT_COEF = 0.01
TARGET_KL = 0.03

# Training run / checkpointing
TOTAL_TIMESTEPS = 1_000_000
CHECKPOINT_FREQ = 10_000
CHECKPOINT_FREQ_MINI = 1_000
