"""
training.py - RL hyperparameters, reward weights, and episode/checkpoint limits.
"""

MEAN_STATS_WINDOW = 20

# Reward weights
BOSS_PARAMETER = 2
DODGE_REWARD = 1.5

PLAYER_PARAMETER = 1
PLAYER_VULNERABILITY_EXP = 2

DEATH_PENALTY = 3
GREEDY_PENALTY = 3

STAMINA_EXP = 3
LOW_STAMINA_PUNISH = 1.0

STEP_PENALTY = 0.05

REWARD_BOSS_DEFEATED = 100.0

# Episode
HISTORY_LENGTH = 24
MAX_STEPS_PER_EPISODE = 500
BOSS_DEFEAT_HP_THRESHOLD = 0.005

# PPO
LEARNING_RATE = 2e-4
N_STEPS = 2048
BATCH_SIZE = 512
N_EPOCHS = 10
GAMMA = 0.96
ENT_COEF = 0.01
TARGET_KL = 0.03

# Training run / checkpointing
TOTAL_TIMESTEPS = 1_000_000
CHECKPOINT_FREQ = 10_000
CHECKPOINT_FREQ_MINI = 1_000
